import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { AppSidebar } from "@/components/layout/Sidebar";
import { ThemeProvider } from "@/components/providers/theme-provider";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={`${inter.variable} h-full antialiased`}
    >
      <body className={`${inter.variable} min-h-full bg-white dark:bg-black`}>
        <ThemeProvider
            attribute="class"
            defaultTheme="dark"
            enableSystem
            disableTransitionOnChange
          >
              <main>
                <div className="min-h-screen">
                  <div className="mx-auto flex max-w-7xl">
                      {/* Left Sidebar */}
                      <aside className="hidden md:block w-[275px]">
                        <div className="fixed top-0 h-screen w-[275px] border-r dark:border-neutral-900 border-neutral-200 px-4">
                          <AppSidebar />
                        </div>
                      </aside>

                      {children}

                  </div>
                </div>
              </main>
        </ThemeProvider>
      </body>
    </html>
  );
}
